name: Travis Lerning Management System

on:
  push:
    branches:
      - "**"

jobs:
  text:
    name: Test Machin
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout in Text Machin
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Depedences
        run: npm install --legacy-peer-deps

      - name: Build Application
        run: npm run build
